### ISSUE TITLE
Encoding problem on Mac with non-US English locale

### ISSUE THREAD

**Issue by katossky** [r-lib/xml2#168]
I run into this problem with a third-party, UTF-8 encoded text file. I can reproduce this error with this code : 

    library(xml2)
    write('<div>Léa Ravon</div>', file='test.html')
    xml_text(read_html('test.html'))

gives:

[1] "LÃ©a Ravon"

One can check that the file created by `write` is correctly encoded using third-party software. (I use Sublime Text.)

R version 3.1.3 (2015-03-09)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

Seems related to issue #54 (on that thread, my problem could not be replicated on a Windows machine).

**Comment by jimhester** [comment]
In this case you just need to specify the file encoding as `UTF-8` explicitly.

```r
library(xml2)
write('<div>Léa Ravon</div>', file='test.html')
xml_text(read_html('test.html'))
#> [1] "LÃ©a Ravon"
xml_text(read_html('test.html', encoding = "UTF-8"))
#> [1] "Léa Ravon"
```
