### ISSUE TITLE
 Memory allocation failed : growing nodeset hit limit  [2]

### ISSUE THREAD

**Issue by randomgambit** [r-lib/xml2#177]
Hello,

I am loading a large `xml` file but I get an error when I try to remove the namespaces.
I have plenty of RAM left. 
```

 xmlfile <- read_xml('P://xml/data-200603.xml')
> xmlfile <- xml_ns_strip(xmlfile)
Error in xpath_search(x$node, x$doc, xpath = xpath, nsMap = ns, num_results = Inf) : 
  Memory allocation failed : growing nodeset hit limit
 [2]****
```
Is that a bug?
Thanks!

**Comment by jimhester** [comment]
I don't know if it is a bug, can you post an xml file that causes the behavior?

**Comment by randomgambit** [comment]
I cannot unfortunately (proprietary data) but I am happy to provide you with any derived statistic you need. Size on disk is about 300MB and I have 128 GB RAM at the moment.

**Comment by baradhili** [comment]
I can post an example..
this is the xslt
`<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="text" />
  <xsl:variable name="FS">
    
    <xsl:text>;</xsl:text>
  </xsl:variable>
  <xsl:variable name="LT">
    
    <xsl:text>&#10;</xsl:text>
  </xsl:variable>
  <xsl:strip-space elements="*" />

<xsl:template match="/">
    <xsl:for-each select="//Chemical[@displayName != '' and @displayName != 'INDEX NAME NOT YET ASSIGNED']">
        <xsl:call-template name="printValues">
            <xsl:with-param name="val1" select="@id" />
            <xsl:with-param name="val2" select="@displayName" />
        </xsl:call-template>
        <xsl:call-template name="printValues">
            <xsl:with-param name="val1" select="@id" />
            <xsl:with-param name="val2" select="normalize-space(NameList/SystematicName/text())" />
        </xsl:call-template>
        <xsl:call-template name="printValues">
            <xsl:with-param name="val1" select="@id" />
            <xsl:with-param name="val2" select="normalize-space(NameList/Synonyms/text())" />
        </xsl:call-template>
    </xsl:for-each>
</xsl:template>
  
  <xsl:template name="printValues">
    <xsl:param name="val1" />
    <xsl:param name="val2" />

    <xsl:text>&#34;</xsl:text>
    <xsl:value-of select="$val1" />
    <xsl:text>&#34;</xsl:text>

    <xsl:text>&#44;</xsl:text>
    <xsl:text>&#34;</xsl:text>https://chem.nlm.nih.gov/chemidplus/sid/startswith/<xsl:value-of select="$val2" /><xsl:text>&#34;</xsl:text>
    <xsl:text>&#44;&#34;nlm&#34;</xsl:text>
    <xsl:text>&#10;</xsl:text>
</xsl:template>

</xsl:stylesheet>`

And its processing an xml file that can be found at ftp://ftp.nlm.nih.gov/nlmdata/.chemidlease/CurrentChemID.xml  be warned its about 850MB

Cheers

**Comment by jimhester** [comment]
I don't think there is anything that can be changed in the R package, it looks like a memory allocation is failing in the libxml2 library.
