### ISSUE TITLE
xml2 install on CENTOS 6.9 x86_64 

### ISSUE THREAD

**Issue by cellsight** [r-lib/xml2#180]
I use to have a old version of centos xml2 in command mode under /usr/local/bin worked great. now with new OS trying to re-install this great program.

I do
devtools::install_github("hadley/xml2")
-bash: syntax error near unexpected token `"hadley/xml2"'

or
install.packages("xml2") bash: syntax error near unexpected token `"xml2"'

I then installed it within R (ver 3.3) and it seems to have installed it but I want the standalone command line xml2 alone. I usually use it after a curl command and pipe into it and it use to generate nice 1 line outputs for me and then used awk after...

Please help!. Thanks

**Comment by jimhester** [comment]
You want to install the [command line xml2 program](https://centos.pkgs.org/6/epel-x86_64/xml2-0.5-7.el6.x86_64.rpm.html). This repo is for the R **xml2** package. Likely you should install the command line program by running something like the following from your shell prompt.

```shell
yum install xml2
```
