### ISSUE TITLE
read_html error in read_connection_ with HTTP 1.0 redirects 

### ISSUE THREAD

**Issue by misea** [r-lib/xml2#182]
### Issue Description and Expected Result
I am making a request to a site that returns a 301 redirect error over HTTP 1.0 protocol with  Connection: close . read_html (and other xml2 methods) fail with a message like this:

```
Error in read_connection_(x, n) : 
  Failure when receiving data from the peer
```

However, if I create the connection with file(), redirects are followed correctly. Similarly download.file follows redirects and setting libcurl option followlocation=TRUE in RCurl also 
works. 

At least some HTTP redirects _are_ followed correctly, so this was confusing.

Wrapping the URL with file() is a simple workaround, but it took me a while to figure that out.

### Reproducible Example
Example:
```r
library('xml2')
library('RCurl')

# This produces an error currently
x <- read_html('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129')

# These work
x <- read_html(file('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129'))
y <- getURL('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129', .opts=c(followlocation=TRUE))
z <- readLines('https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129')

# Note that this works, so redirects are followed sometimes (HTTP 1.1 & keepalive)
read_html('http://httpbin.org/redirect-to?url=http://httpbin.org/html?status_code=301')
```

I don't have another http 1.0 redirecting endpoint. In case that one changes, the headers returned are

```
HTTP/1.0 301 MOVED PERMANENTLY
Date: Wed, 19 Jul 2017 20:55:54 GMT
Server: Apache/2.2.15 (Red Hat)
Content-Length: 0
Location: https://digital.library.unt.edu/ark%3A/67531/metadc29275/m1/129/
Vary: Accept-Encoding
Access-Control-Allow-Origin: *
Connection: close
Content-Type: text/html; charset=utf-8
```

<details>
<summary>Session Info</summary>

```r
Session info ---------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-07-19                  

Packages ------------------------------------------------------------------------------------------
 package   * version  date       source        
 base      * 3.3.3    2017-03-07 local         
 bitops    * 1.0-6    2013-08-17 CRAN (R 3.3.0)
 curl        2.7      2017-06-26 CRAN (R 3.3.2)
 datasets  * 3.3.3    2017-03-07 local         
 devtools  * 1.13.2   2017-06-02 CRAN (R 3.3.2)
 digest      0.6.12   2017-01-27 CRAN (R 3.3.2)
 graphics  * 3.3.3    2017-03-07 local         
 grDevices * 3.3.3    2017-03-07 local         
 memoise     1.1.0    2017-04-21 CRAN (R 3.3.2)
 methods   * 3.3.3    2017-03-07 local         
 Rcpp        0.12.11  2017-05-22 CRAN (R 3.3.2)
 RCurl     * 1.95-4.8 2016-03-01 CRAN (R 3.3.0)
 stats     * 3.3.3    2017-03-07 local         
 tools       3.3.3    2017-03-07 local         
 utils     * 3.3.3    2017-03-07 local         
 withr       1.0.2    2016-06-20 CRAN (R 3.3.0)
 xml2      * 1.1.1    2017-01-24 CRAN (R 3.3.2)#> output
```
</details>

**Comment by jimhester** [comment]
This looks to actually be an issue with [curl](https://github.com/jeroen/curl) or possibly with the server you are trying to connect to, as the curl examples clearly show it supports redirects.

Here is a reproducible example without any xml2 code

``` r
readLines(curl::curl("https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129"))
#> Error in readLines(curl::curl("https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129")): Failure when receiving data from the peer
```

**Comment by jennybc** [comment]
I have also found some problems with curl 2.7 (they manifest differently). I would see if you can reproduce this with curl 2.6 or the current dev version. I think a new release is imminent.

**Comment by misea** [comment]
Thanks. I tried this with the current dev version of curl and it manifests differently: SSLRead error -9806. I'll enter an issue on curl and see what they say.

**Comment by jeroen** [comment]
The server has malconfigured gzip compression. Somehow only OSX SecureSSL chokes on this.

I can reproduce the problem via the command line on OSX:

```sh
curl -v -H 'Accept-Encoding: gzip,deflate' https://digital.library.unt.edu
```
To workaround in R, disabling gzip compression:

```r
h <- curl::new_handle(accept_encoding = NULL)
readLines(curl::curl("https://digital.library.unt.edu/ark:/67531/metadc29275/m1/129", handle = h))
```

**Comment by jeroen** [comment]
The folks at libcurl are certain this is a server misconfiguration problem. I have send the sysadmin a message. Other than that there is nothing you can do but disable gzip for this server.

**Comment by jimhester** [comment]
Thanks @jeroen, looks like there is nothing else to be done here.
