### ISSUE TITLE
Installation fails on macOS, with Xcode 9 installed

### ISSUE THREAD

**Issue by pkrog** [r-lib/xml2#191]
Under macOS Sierra 10.12.6 (16G29), using Xcode Version 9.0 (9A235), the following error is met when installing xml2 package:
```
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -L/usr/local/Cellar/r/3.4.2/lib/R/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o xml2.so RcppExports.o connection.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm -L/usr/local/Cellar/r/3.4.2/lib/R/lib -lR -lintl -Wl,-framework -Wl,CoreFoundation
ld: file not found: /usr/lib/system/libsystem_darwin.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [xml2.so] Error 1
ERROR: compilation failed for package ‘xml2’
* removing ‘/Users/pierrick/Library/R/3.4/library/xml2’
```

**Comment by pigboysid** [comment]
I followed the instructions on ticket 191, which linked me to the post at https://stat.ethz.ch/pipermail/r-sig-mac/2016-September/012046.html:
* I copied `/usr/bin/xml2-config` to somewhere earlier in my path (in my case, `/Users/jcherry/bin`).
* I edited line 3 of the file: instead of `prefix=$(xcrun -show-sdk-path)/usr`, I changed it to `prefix=/usr`.

Following those two steps allowed `install.packages('xml2')` to complete successfully.

**Comment by paul-riley** [comment]
Thanks @pigboysid! I just stumbled into this error and it fixed the linking issue I ran into.

**Comment by kobeontheway** [comment]
I have the same problem ,you can try to reset the command line:
sudo xcode-select -s /Library/Developer/CommandLineTools

**Comment by nazamy** [comment]
Thanks a bunch man!

**Comment by plijnzaad** [comment]
> sudo xcode-select -s /Library/Developer/CommandLineTools

worked a treat, thanks!

**Comment by picoPWR** [comment]
> sudo xcode-select -s /Library/Developer/CommandLineTools

Ran into this not too long ago. Works great!

**Comment by patirasam** [comment]
> sudo xcode-select -s /Library/Developer/CommandLineTools

Thanks! It worked for me.
