### ISSUE TITLE
xml_text ignore google ads script tag

### ISSUE THREAD

**Issue by salimk** [r-lib/xml2#195]
### Issue Description and Expected Result
xml_text( )  should remove <script> tag and what in between, especially google ads like
```
<script>
   (adsbygoogle = window.adsbygoogle \|\| []).push({});
</script>
```
Example 
```
x <- xml2::read_html("http://forum.zebulon.fr/conseil-performances-optimisees-t219478.html"   )
  b <- xml_text(xml_find_all(x, "//*/div[@class='post_body']"))
  b[2]
```

it returns 
`"\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t(adsbygoogle = window.adsbygoogle || []).push({});\n\t\t\t\t\t"`

**Comment by jimhester** [comment]
You will need to remove the script blocks manually in a preprocessing step.

``` r
library(xml2)
x <- read_html("http://forum.zebulon.fr/conseil-performances-optimisees-t219478.html")
invisible(xml_remove(xml_find_all(x, "//script")))
b <- xml_text(xml_find_all(x, "//*/div[@class='post_body']"))
b[2]
#> [1] "\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t\t\tInscrivez-vous au forum gratuitement et profitez de nombreux avantages ! \n\t\t\t\t\n\t\t\t"
```

**Comment by VictorSuarezL** [comment]
Hi, first of all nice package (Rcrawler). I've some issue, just for test the parameter `Obeyrobots` I tried to scrap a site which is in a path not allowed in the robots.txt file, and the function gave me the html file, why it happens? Is there some exceptions to that Obeyrobots doesn't take into account? Thanks in advance!
