### ISSUE TITLE
No way to set the value of an attribute to the empty string

### ISSUE THREAD

**Issue by chrislad** [r-lib/xml2#198]
It doesn't seem to be possible to set the value of an attribute to the empty string. This is valid XML and there's no problem parsing such an attribute:

```r

library(xml2) # v.1.1.1

# reading
x <- read_xml("<a foo='' />")
n <- xml_find_first(x, "/a")
xml_attrs(n) # named character vector of length 1

# writing
xml_set_attr(n, "foo", "bar")
xml_attrs(n) # named character vector of length 1

xml_set_attr(n, "foo", "")
xml_attrs(n) # named character vector of length 0
```
Is there another way to set the value of the attribute to the empty string?

**Comment by jimhester** [comment]
Sorry, this was a deficiency in the implementation, should now be fixed.
