### ISSUE TITLE
read_html causes R session to abort

### ISSUE THREAD

**Issue by mkhezr** [r-lib/xml2#199]
Take the following url:
"https://www.ubcic.bc.ca/louisemandellcollection"

using `read_html` with the url causes R session to **abort**:
`read_html("https://www.ubcic.bc.ca/louisemandellcollection")`

using `read_xml` with the url shows the following error:
`read_xml("https://www.ubcic.bc.ca/louisemandellcollection")`
`Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  Opening and ending tag mismatch: link line 58 and head [76]`

**Comment by jimhester** [comment]
Thank you for opening the issue, this should now be fixed in the devel version of xml2.
