### ISSUE TITLE
How to efficiently detect parsing errors with xml2?

### ISSUE THREAD

**Issue by dleutnant** [r-lib/xml2#200]
Hi all, 

I recently had to parse tons of XML files which mostly were all right. But occasionally, there were parsing errors due to file errors or incomplete XML nodes (I know that those files shouldn't be named _valid_). And if I have an incomplete XML file, `xml2::read_xml` crashes my R instance with a seq_fault.

> *** caught segfault ***
> address 0x0, cause 'unknown'
> 
> Traceback:
>  1: .Call("xml2_doc_parse_raw", PACKAGE = "xml2", x, encoding, base_url,     as_html, options)
>  2: doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,     options = options)
>  3: read_xml.raw(raw, encoding = encoding, base_url = base_url, as_html = as_html,     options = options)
>  4: read_xml.connection(con, encoding = encoding, ..., as_html = as_html,     base_url = x, options = options)
>  5: read_xml.character(x = x, options = "RECOVER", verbose = TRUE)
>  6: xml2::read_xml(x = x, options = "RECOVER", verbose = TRUE)
>  7: doTryCatch(return(expr), name, parentenv, handler)
>  8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
>  9: tryCatchList(expr, classes, parentenv, handlers)
> 10: tryCatch(xml2::read_xml(x = x, options = "RECOVER", verbose = TRUE), error = function(e) e)

I found in the {XML} package `XML::getXMLErrors`, which perfectly works in my case: Either I get an empty list (`list()`) or a list with errors describing the reason.

Because I like the idea of xml2, I was wondering whether there is a similar way in the {xml2} package? I've checked the parsing options of `xml2::read_xml` but wasn't really succesful.

Any help or advice is greatly appreciated!
Thanks!

**Comment by jimhester** [comment]
The crashes are likely caused by the same issue as https://github.com/r-lib/xml2/issues/199. It is now fixed in the devel verson of xml2. I would suggest trying that version.

**Comment by dleutnant** [comment]
Indeed, that addresses the issue! Thanks for your quick response!
