### ISSUE TITLE
Insert space between text nodes

### ISSUE THREAD

**Issue by cainesap** [r-lib/xml2#201]
Hello,
Thank you for xml2, it's a great library!
I have a question about multiple text nodes and how to insert a space between them:
e.g.
```
x <- read_xml("<foo> <bar>some<baz/>text</bar> </foo>")
xml_text(x)
# [1] "sometext"
```
How can I produce "some text" as output of the above?
Sorry, this seems like a straightforward task but I'm scratching my head about it.
thanks in advance, Andrew

**Comment by jimhester** [comment]
You need to select the text nodes explicitly, then paste them together, e.g.

``` r
library(xml2)
x <- read_xml("<foo> <bar>some<baz/>text</bar> </foo>")
text_nodes <- xml_find_all(x, "//text()")
paste(xml_text(text_nodes), collapse = " ")
#> [1] "some text"
```

Created on 2018-01-04 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
