### ISSUE TITLE
Bash not installed, list as dependency?

### ISSUE THREAD

**Issue by kenahoo** [r-lib/xml2#202]
On Alpine Linux, `bash` isn't part of the base install, but `sh` is.  That means the `configure` script throws the error `sh: ./configure: No such file or directory` until the `bash` package is installed (see #178).

Is it feasible to add `bash` to the `SystemRequirements` section of `DESCRIPTION`, or is that only for libraries?

**Comment by jimhester** [comment]
Seems to be a pretty niche case to me, bash is pretty universal.

**Comment by kenahoo** [comment]
Sure, but when it's not there, it's not there.  A hint to install it would be nice, otherwise it's not clear at all what went wrong.

Alpine Linux is a very stripped-down Linux with the aim of making very small Docker containers, etc.  It's good for creating automated build containers, etc.  An Alpine Linux image with R, devtools, Rcpp, roxygen2, and testthat installed is 635MB.  By comparison, a CentOS Linux image with the same things installed is 1.73GB.  I'd expect that as container testing gets more common, you might see people hitting this more often.

**Comment by jimhester** [comment]
Closed by ba53a87c3ef9, we now use only sh in the configure script.
