### ISSUE TITLE
can't install this package on R 3.4.1

### ISSUE THREAD

**Issue by IndyYan** [r-lib/xml2#205]
It warn that  package ‘xml2’ is not available (for R version 3.4.1)

**Comment by IndyYan** [comment]
It warn than  package ‘xml2’ is not available (for R version 3.4.1)

**Comment by hadley** [comment]
The development version fixes this problem and has been submitted to CRAN sometime ago. Unfortunately it is currently stuck in limbo and there's nothing we can do.
