### ISSUE TITLE
Problems in installing xml2 package on Windows 10

### ISSUE THREAD

**Issue by terysetn** [r-lib/xml2#218]
### Issue Description and Expected Result
I have an issue with installing xml2 package on Windows 10.
I used devtools::install_github("r-lib/xml2") command but received the following results

### Reproducible Example
 devtools::install_github("r-lib/xml2")
Downloading GitHub repo r-lib/xml2@master
from URL https://api.github.com/repos/r-lib/xml2/zipball/master
Installing xml2
Installing 1 package: Rcpp
Installing package into ‘\\CNAS.RU.NL/U758207/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rcpp_0.12.16.zip'
Content type 'application/zip' length 4371941 bytes (4.2 MB)
downloaded 4.2 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\u758207\AppData\Local\Temp\RtmpyASPgj\downloaded_packages
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/u758207/AppData/Local/Temp/RtmpyASPgj/devtools1c0c75c81609/r-lib-xml2-bb6efb2"  \
  --library="\\CNAS.RU.NL/U758207/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'xml2' ...
** libs

*** arch - i386
rm -f RcppExports.o connection.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o xml2.dll
"C:/PROGRA~1/R/R-34~1.1/bin/i386/Rscript.exe" --vanilla "../tools/winlibs.R"
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG -I../inst/include -I../windows/libxml2-2.9.4/include/libxml2 -DLIBXML_STATIC -I"\\CNAS.RU.NL/U758207/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:0:
../inst/include/xml2_types.h:5:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xml2.dll" OBJECTS="RcppExports.o connection.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o"' had status 2
ERROR: compilation failed for package 'xml2'
* removing '\\CNAS.RU.NL/U758207/Documents/R/win-library/3.4/xml2'
Installation failed: Command failed (1)
<details>
<summary>Session Info</summary>

```r
devtools::session_info() # Paste output below
The session info is as follows

 sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.1  R6_2.2.2        tools_3.4.1     withr_2.1.2     curl_3.2        memoise_1.1.0   grid_3.4.1     
 [9] git2r_0.21.0    digest_0.6.15   devtools_1.13.5 lattice_0.20-35

```
</details>

**Comment by jimhester** [comment]
I think this may be an issue with where your R library is being installed e.g. `\CNAS.RU.NL/U758207/Documents/R/win-library/3.4` You might try installing the packages to a physical drive rather than a network share

**Comment by terysetn** [comment]
@jimhester , it worked! Oh, thank you.
