### ISSUE TITLE
xml2 install issue on Centos 7

### ISSUE THREAD

**Issue by connieshen0503** [r-lib/xml2#219]
When install "xml2" package in R 

`install.packages("xml2")`

Error:

`
Error : /tmp/Rtmpw60aCp/R.INSTALL7819efef27e/xml2/man/read_xml.Rd:47: unable to load shared object '/usr/lib64/R/library/xml2/libs/xml2.so':
libicui18n.so.58: cannot open shared object file: No such file or directory
ERROR: installing Rd objects failed for package ‘xml2’
removing ‘/usr/lib64/R/library/xml2’
The downloaded source packages are in ‘/tmp/RtmpmkE6HT/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("xml2") :
installation of package ‘xml2’ had non-zero exit status 
`

SessionInfo:

`
R version 3.4.3 (2017-11-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)
Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3
 `

**Comment by jimhester** [comment]
It looks like your shared library is linking to libicui18n.so.58, but this does not exist on your system. I don't think this is an issue with the xml2 package. Rather something is misconfigured on your system.

**Comment by connieshen0503** [comment]
Thanks, problem fixed. 
I will close the issue.

**Comment by jnolis** [comment]
I'm having this same issue, any chance you could share what you fixed @connieshen0503?

**Comment by dorianps** [comment]
Same problem here.

**Comment by dorianps** [comment]
Ehm, fixed the issue by adding the anaconda lib path to the system ld path:

```
locate libicui18n.so.58
#/opt/anaconda2/envs/python3/lib/libicui18n.so.58
#/opt/anaconda2/envs/python3/lib/libicui18n.so.58.2
#/opt/anaconda2/lib/libicui18n.so.58
#/opt/anaconda2/lib/libicui18n.so.58.2
#/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58
#/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58.2

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda2/lib/
```

**Comment by PumpkinL** [comment]
> 
> 
> I'm having this same issue, any chance you could share what you fixed @connieshen0503?

I solved this problem by downloading ICU4C 58.2 from : http://site.icu-project.org/download

and compiled. Then added the library location to $LD_LIBRARY_PATH, the install will be work

**Comment by nielsenmarkus11** [comment]
I was able to fix this issue by removing anaconda completely from my PATH and LD_LIBRARY_PATH environment variables.

**Comment by Christophe-Freyre** [comment]
This solved it for me: [(https://github.com/igraph/rigraph/issues/274#issuecomment-497985312)]

**Comment by ksens** [comment]
Faced this problem today on CentOS Linux release 7.9.2009 (Core).

First, I tried the solution listed at https://github.com/r-lib/xml2/issues/219#issuecomment-419601007 i.e.

```sh
locate libicui18n.so.58
# ... my results pointed to anaconda3, so I set

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda3/lib/
```

... but this did not work. 

Then I followed up on the solution at https://github.com/r-lib/xml2/issues/219#issuecomment-765727827, and proceeded to completely remove `anaconda3` from my system. This resolved the problem.

**Comment by maximus-sci** [comment]
> Ehm, fixed the issue by adding the anaconda lib path to the system ld path:
> 
> ```
> locate libicui18n.so.58
> #/opt/anaconda2/envs/python3/lib/libicui18n.so.58
> #/opt/anaconda2/envs/python3/lib/libicui18n.so.58.2
> #/opt/anaconda2/lib/libicui18n.so.58
> #/opt/anaconda2/lib/libicui18n.so.58.2
> #/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58
> #/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58.2
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda2/lib/
> ```

I've been trying to solve this issue for hours. This worked, thank you!

**Comment by xyz0202** [comment]
Hi, I met the same error too. And I use "locate libicui18n.so.58" to find the directory, it shows nothing. But I find its location under anaconda. I tried to add the path to LD_LIBRARY_PATH by export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:the directory I found. It does not work. Does anybody know how to fix it?

**Comment by jianwu1** [comment]
> Hi, I met the same error too. And I use "locate libicui18n.so.58" to find the directory, it shows nothing. But I find its location under anaconda. I tried to add the path to LD_LIBRARY_PATH by export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:the directory I found. It does not work. Does anybody know how to fix it?

You need to add export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda3/lib/ to the .r_bashrc file rather than the .bashrc file under your root directory. export automatically add to .bashrc I think. You can edit .r_bashrc file by loading an R package "usethis", and run: `usethis::edit_file("~/.r_bashrc")`.

**Comment by jianwu1** [comment]
> Ehm, fixed the issue by adding the anaconda lib path to the system ld path:
> 
> ```
> locate libicui18n.so.58
> #/opt/anaconda2/envs/python3/lib/libicui18n.so.58
> #/opt/anaconda2/envs/python3/lib/libicui18n.so.58.2
> #/opt/anaconda2/lib/libicui18n.so.58
> #/opt/anaconda2/lib/libicui18n.so.58.2
> #/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58
> #/opt/anaconda2/pkgs/icu-58.2-h9c2bf20_1/lib/libicui18n.so.58.2
> 
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/anaconda2/lib/
> ```

Thank you! I fixed this problem by exporting the path to the directory where libicui18n.so.58 is located to the .r_bashrc file under the root directory and restart R.
