### ISSUE TITLE
xml standalone property

### ISSUE THREAD

**Issue by the-knife** [r-lib/xml2#220]
Hello,
I can't find the way to add a **standalone="yes"** property in the xml_document.
Did I miss something in the package documentation?

**Comment by the-knife** [comment]
Still interested by the answer, one year later...

**Comment by jimhester** [comment]
It might help if you give a little more context with a simple example document you are trying to create. 

This sort of question could also be a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by pmlefeuvre-met** [comment]
I am also wondering if one could add `standalone=yes` to the xml header, currently xml2 has only the option to add `version` and `encoding`: 
```R
> doc <- xml_new_document()
> as(doc, "character")
[1] "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
```
When I am required to have: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
```
