### ISSUE TITLE
xml_attr()<-is mishandling xml_nodesets

### ISSUE THREAD

**Issue by eamoncaddigan** [r-lib/xml2#221]
When assigning a character vector to an xml_nodeset using `xml_attr()<`-, the first element in the vector is assigned to all nodes. This is different than, e.g., `xml_text()<-`, which allows different values to be assigned to different nodes.

### Reproducible Example
```r
library(xml2)
x <- read_xml("<x><a b='c'/><a b='d'/></x>")
a_set <- xml_find_all(x, "a")
# Doesn't work as expected
xml_attr(a_set, "b") <- c("e", "f")
xml_attr(a_set, "b")
#> [1] "e" "e"
# Also doesn't work as expected
xml_set_attr(a_set, "b", c("g", "h"))
xml_attr(a_set, "b")
#> [1] "g" "g"
```

I understand that `xml_attrs()` can be used to set the same attribute for multiple nodes. However, since the current behavior is (IMO) unexpected I believe it should at least be reflected in the documentation.

**Comment by jimhester** [comment]
I think you are right, `xml_attr<-` should be recycling the attributes.
