### ISSUE TITLE
Configuration failed for package xml2

### ISSUE THREAD

**Issue by cryptic0** [r-lib/xml2#223]
```r

> install.packages('xml2')
Installing package into ‘/usr/local/lib/R/3.4/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/xml2_1.2.0.tar.gz'
Content type 'application/x-gzip' length 251614 bytes (245 KB)
==================================================
downloaded 245 KB

* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/libxml2
Using PKG_LIBS=-L/usr/lib -lxml2 -lz -lpthread -licucore -lm
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/usr/local/lib/R/3.4/site-library/xml2’

The downloaded source packages are in
	‘/private/var/folders/_g/sqvygqgn1pn69qm3mmbtp5hh0000gn/T/Rtmp8BskUb/downloaded_packages’
Warning message:
In install.packages("xml2") :
  installation of package ‘xml2’ had non-zero exit status



```

**Comment by batpigandme** [comment]
Based on the error message, it looks like you don't have libxml-2.0 on your machine or in the package config path:
```r
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
```

**Comment by cryptic0** [comment]
It must not be in the path then, because I do have it installed.

```bash
brew install libxml2
Warning: libxml2 2.9.7 is already installed and up-to-date
```

**Comment by afang8** [comment]
Try going to /usr/lib/x86_64-linux-gnu/pkgconfig and copying the libxml-2.0.pc file into /usr/lib/pkgconfig

**Comment by afang8** [comment]
Try copying the libxml-2.0.pc file from /usr/lib/x86_64-linux-gnu/pkgconfig to /usr/lib/pkgconfig! This worked for us when we were trying to install xml2 on RStudio Server on a EC2 instance.

**Comment by santangelo** [comment]
> Configuration failed because libxml-2.0 was not found. Try installing:
> * deb: libxml2-dev (Debian, Ubuntu, etc)
> * rpm: libxml2-devel (Fedora, CentOS, RHEL)
> * csw: libxml2_dev (Solaris)

I had the same issue. I had the instruction right in front of me... I just had to type:
`sudo apt-get install libxml2-dev`
It worked perfectly.

By the way, if I typed 
`sudo apt-get install libxml2` , that gave me the answer:
> Warning: libxml2 2.9.7 is already installed and up-to-date

Hope that helps.

**Comment by cryptic0** [comment]
That solution only works on Ubuntu, not on OSX.

**Comment by swvanderlaan** [comment]
This seems relevant: https://www.perfectlyrandom.org/2015/12/13/install-xml2-r-package-on-macos/#fn:1.

**Comment by bteed** [comment]
Seems to be fixed in development version. I was having the same problem installing from CRAN, but `devtools::install_github("r-lib/xml2")` works. 

(I'm running macOS Mojave 10.14.4 and package management is primarily through home brew but I have Xcode installed through the App Store.)

**Comment by sbibauw** [comment]
> Seems to be fixed in development version. I was having the same problem installing from CRAN, but `devtools::install_github("r-lib/xml2")` works.

While this was also the correct direction in my case (macOS 10.14.4, R 3.6, brewed `libxml2`), the devtools install failed, but the following equivalent did work (not exactly sure why...):

    install.packages("https://github.com/hadley/xml2/archive/master.tar.gz", type = "source", repos = NULL)

**Comment by jpeacock29** [comment]
On OSX 10.14.5, R 3.6.1 and `libxml2` installed via `xcode-select`, this problem can also be solved by giving `xml2` a hint on where to find `libxml2`. In my case,

**Comment by CorleoneZ** [comment]
i got this problem :

> configure: error :libxml is required by gpcloud

i can't solve it

**Comment by CorleoneZ** [comment]
and this:
> configure:error : library 'gpos' is required for GPORCA

**Comment by jyspring** [comment]
exactly the same error, and the same problem!
still can not fix it! looking forward to any help!

**Comment by mohamed-aiman** [comment]
Even though it seems that libxml is installed, had to reinstall manually to make it work.

```
wget ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz
tar xvzf libxml2-2.9.2.tar.gz
cd libxml2-2.9.2
./configure --prefix=/usr --disable-static --with-history && make
sudo make install
```

**Comment by xyslope** [comment]
I had the same errors.
And finally, I solved the problem with the following command.

install.packages("tidyverse", INSTALL_opts = '--no-lock')

In my rstudio-server messages, it said that there are some permission problem for lock files.
I don't know why the error happens because I tried all the relevant directory to be world writable (777) and still got the same error.

Well, with --no-lock option, I could install tidyverse.

**Comment by pradip-gubhaju** [comment]
guys! just run this one.
sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev


BOOM - thanks me later!

**Comment by graveyardkeeper** [comment]
> guys! just run this one.
> sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev

> BOOM - thanks me later!

This worked for me. Thank you so much!

**Comment by Ewnetu8** [comment]
> guys! just run this one. sudo apt install libcurl4-openssl-dev libssl-dev libxml2-dev
> 
> BOOM - thanks me later!

Wonder full!!!!!!!!!!! Thank you it is also work for me.

**Comment by Mr-Breeze** [comment]
> > Configuration failed because libxml-2.0 was not found. Try installing:
> > 
> > * deb: libxml2-dev (Debian, Ubuntu, etc)
> > * rpm: libxml2-devel (Fedora, CentOS, RHEL)
> > * csw: libxml2_dev (Solaris)
> 
> I had the same issue. I had the instruction right in front of me... I just had to type: `sudo apt-get install libxml2-dev` It worked perfectly.
> 
> By the way, if I typed `sudo apt-get install libxml2` , that gave me the answer:
> 
> > Warning: libxml2 2.9.7 is already installed and up-to-date
> 
> Hope that helps.

Worked perfectly for me, thank you.

**Comment by jmath1983** [comment]
> Based on the error message, it looks like you don't have libxml-2.0 on your machine or in the package config path:
> 
> ```r
> Configuration failed because libxml-2.0 was not found. Try installing:
>  * deb: libxml2-dev (Debian, Ubuntu, etc)
>  * rpm: libxml2-devel (Fedora, CentOS, RHEL)
>  * csw: libxml2_dev (Solaris)
> ```

This one solved for me.
