### ISSUE TITLE
Parsing time (XML to data.frame)

### ISSUE THREAD

**Issue by mikgh** [r-lib/xml2#224]
Posted following on StackOverflow - but may be more relevant here (since it is package-specific):
Converting OIOIUBL invoices from XML to a dataframe in R I am using the code below (sample XML-file is in the link further down).

When iterating over 323.859 files the XML-to-dataframe parsing takes 64 minutes. From the code below how could this be optimized? The same task using Python takes ~6 minutes (sorry for being unable to share the Python-code).

I am aware that R is not good at moving lots of data in-memory. But can the difference of 58 minutes in execution time be attributed to this or my lacking programming skills?

Example:
```r
library(xml2)
readinvoice <- function(nextfile) {
    tryCatch(doc <- read_xml(nextfile, options = c("RECOVER", "HUGE")),
            error = function(e) {print(paste("Error in code", basename(nextfile), e$message))})
    art <- xml_name(doc)
    path <- xml_path(doc)
    ID <- gsub('\\.xml', "", basename(nextfile))
    priceTotal <- xml_double(xml_find_all(doc, "./cac:LegalMonetaryTotal/cbc:PayableAmount"))
    tryCatch(df <- data.frame(cbind(art, path, ID, priceTotal)),
            error = function(e) {print(paste("Error in code", bilagsident, e$message))})
    }
xmlfilelist <- list.files("PATH/TO/FILES", full.names = TRUE)
result <- lapply(xmlfilelist, readinvoice) # THIS LINE IS SLOW
```
Link to sample file: https://1drv.ms/u/s!Am4CDwbz-dfchPZKhf9RQPSfnKcLeg

Thanks for any help you may provide.

Best regards,
Mikkel

**Comment by jimhester** [comment]
It is hard to say why without seeing the python code. However I would suggest you post this on https://community.rstudio.com to see if you get any suggestions on how to speed things up.
