### ISSUE TITLE
FR: file argument for xml_structure

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xml2#244]
`xml_structure` is great, but the `cat` output can get quite long...

As opposed to `write_xml`, `file` argument adds flexibility to shut this argument on/off without changing much else while using `xml_structure`.

Would be straightforward to add since this argument can just be passed to `cat` directly, IIUC.

Happy to try out a PR if it sounds like a good idea.

**Comment by jimhester** [comment]
Passing the dots to `cat()` seems fine to me, happy to review a PR if you would like!
