### ISSUE TITLE
xsd comment causes node to be empty

### ISSUE THREAD

**Issue by earnaud** [r-lib/xml2#260]
### Issue Description and Expected Result
I use the xml2 package to read xsd files, which perfectly work on the first ones I worked with (https://github.com/NCEAS/eml). But I wanted to give a try with the standard "Observation & Measurement" and its xsd specification (http://schemas.opengis.net/om/2.0/observation.xsd). It happens that this has a comment inserted in an element ("phenomenonTime") and parsing it with the `read_xml` function and then turning it into a list with `as_list` renders an empty node (contains a `list()`). 

### Reproducible Example
You can try to download the file "observation.xsd" (link above) and just execute the following lines:
```r
library(xml2)
x <- as_list(read_xml("observation.xsd"))
View(x)
# this didn't work for me
```
and then edit "observation.xsd" to remove the comment in "phenomenonTime". Then it worked for me.

I don't think I already saw this issue posted before but I might have skipped it.

**Comment by jimhester** [comment]
Sorry, I can't reproduce the issue, I think perhaps the original document was malformed and has since been fixed.
