### ISSUE TITLE
Function to extract HTML tables

### ISSUE THREAD

**Issue by georgevbsantiago** [r-lib/xml2#266]
Hello, thanks for developing the package.

Is developing a table extracting function from HTML files something planned for the `xml2` package?

In the `rvest` package, the `rvest::html_table` function attempts to accomplish this task, but is still very slow and has consistency issues in the data structure. I pointed this out to [issue 273 of the rvest package](https://github.com/tidyverse/rvest/issues/237)

In the `XML` package, the `XML::readHTMLTable` function does the job of extracting tables (at least in the tests I did), with good data speed and consistency.

Table extraction in HTML files is apparently not trivial. There are other interesting packages like [htmltab](https://cran.r-project.org/web/packages/htmltab/index.html) that try to cover this gap in the R ecosystem.

A function for this purpose would be very useful. The `rvest` package has 1,083 stars in github (the third most voted package in the repository), but its development is slower than other TidyVerse packages and relies heavily on `xml2`. In addition, a function for this purpose would help in the [Migration guide for XML package](https://github.com/r-lib/xml2/issues/246).

Thanks for listening.

**Comment by hadley** [comment]
This functionality will stay in rvest.
