### ISSUE TITLE
url_relative test fails with libxml2 2.9.10

### ISSUE THREAD

**Issue by QuLogic** [r-lib/xml2#277]
### Issue Description and Expected Result
The [automatic rebuilds](https://apps.fedoraproject.org/koschei/package/R-xml2?collection=f32) fail again with the [libxml2 2.9.10 release](https://koschei.fedoraproject.org/build/7163911).

### Reproducible Example
Run build (including tests) on Fedora Rawhide or other system with libxml2 2.9.10.

```r
Last 13 lines of output:
  > 
  > test_check("xml2")
  This is libxml2 version 2.9.10 
  -- 1. Failure: url_relative (@test-url.R#22)  ----------------------------------
  url_relative("http://hadley.nz/a/c", "http://hadley.nz/") not equal to "../a/c".
  1/1 mismatches
  x[1]: "a/c"
  y[1]: "../a/c"
  
  == testthat results  ===========================================================
  [ OK: 390 | SKIPPED: 4 | WARNINGS: 0 | FAILED: 1 ]
  1. Failure: url_relative (@test-url.R#22) 
```

I guess this is because the fix in 9b5426e5cc9ae1d4eed0ec72f92f38c2cd350916 does a string comparison of versions, for which '2.9.10' < '2.9.9'. I'm not sure how you can do a proper semver comparison in R.

<details>
<summary>Session Info</summary>
It's an automated build, so I can't really get this, sorry. You can check the root.log in the build link above for installed packages.
</details>

**Comment by jimhester** [comment]
Thanks, should now be fixed!

**Comment by QuLogic** [comment]
Thanks for the quick [fix](https://koji.fedoraproject.org/koji/buildinfo?buildID=1408354).
