### ISSUE TITLE
Cannot create child node with attribute 'par'

### ISSUE THREAD

**Issue by chohm** [r-lib/xml2#284]
Hello,

I need to write a data export into a specified xml format. Therrefore I need to create a node with the attribute 'par'.

Here's an example
```r
library("xml2")
r <- xml2::xml_new_root("test")

xml2::xml_add_child(r,
                    .value = "a",
                    "abc" = "b")

xml2::xml_add_child(r,
                    .value = "a",
                    "par" = "b")
```

returns:
`Error: $ operator is invalid for atomic vectors`

Any help or explanation appreciated.

Best,
Christian

----------------------------

xml2 version is:
`packageVersion("xml2")
[1] ‘1.2.2’`

R version is:
`R.Version()
$platform
[1] "x86_64-suse-linux-gnu"

$arch
[1] "x86_64"

$os
[1] "linux-gnu"

$system
[1] "x86_64, linux-gnu"

$status
[1] ""

$major
[1] "3"

$minor
[1] "4.2"

$year
[1] "2017"

$month
[1] "09"

$day
[1] "28"

$`svn rev`
[1] "73368"

$language
[1] "R"

$version.string
[1] "R version 3.4.2 (2017-09-28)"

$nickname
[1] "Short Summer"`

**Comment by jennybc** [comment]
I happened to pause here because I was looking for an error to debug for a talk I'm preparing. Here's more detail (which lead to a quick PR).

```
> library("xml2")
> 
> r <- xml2::xml_new_root("test")
> 
> xml2::xml_add_child(r,
+                     .value = "a",
+                     "abc" = "b")
> 
> xml2::xml_add_child(r,
+                     .value = "a",
+                     "par" = "b")
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In create_node(.value, .x, .copy = .copy, ...) :
  partial argument match of 'par' to 'parent'
Run `rlang::last_error()` to see where the error occurred.
> 
> rlang::last_trace()
<error/rlang_error>
Error: $ operator is invalid for atomic vectors

Backtrace:
    █
 1. ├─xml2::xml_add_child(r, .value = "a", par = "b")
 2. ├─xml2::xml_add_child.xml_document(r, .value = "a", par = "b") R/xml_modify.R:142:2
 3. ├─base::NextMethod("xml_add_child") R/xml_modify.R:169:4
 4. └─xml2::xml_add_child.xml_node(r, .value = "a", par = "b")
 5.   └─xml2::create_node(.value, .x, .copy = .copy, ...) R/xml_modify.R:148:2
 6.     └─base::structure(...) R/xml_modify.R:128:4
```

Ironically, it's not easy for me to use reprex here _and_ show the backtrace 😬
