### ISSUE TITLE
Issue installing xml2 on debian

### ISSUE THREAD

**Issue by marisolosman** [r-lib/xml2#286]
I have this issue installing xml2
```r
Error :  unable to load shared object '/home/osman/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-xml2/00new/xml2/libs/xml2.so':
  /home/osman/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-xml2/00new/xml2/libs/xml2.so: undefined symbol: xmlFree
```
I specified the location of libxml2-dev
Details of the session
Running  R version 3.6.0 and Rstudio 1.0.153
Debian 9.9

**Comment by MrPhilosopher** [comment]
any updates? @marisolosman 
I'm also having similar issue.

**Comment by marisolosman** [comment]
So far, no updates

**Comment by MrPhilosopher** [comment]
Hi @marisolosman ,

I have resolved my issue by following this article: https://www.brodrigues.co/blog/2019-05-18-xml2/

I already had anaconda3 installed so just had to pass the path and once it worked I passed the path permanently into the config file.

Please see if it can help in your case as well.

**Comment by jimhester** [comment]
xmlFree is a symbol defined by the upstream libxml2 library, so likely you have some issue with your shared library load path or similar. I don't think this is a bug in the xml2 R package.
