### ISSUE TITLE
XML2 library: Question about correct usage of library, or have I found a bug related to performance

### ISSUE THREAD

**Issue by biopaw** [r-lib/xml2#298]
I posted in the community and still waiting for anyones input, I dont know that anyone will respond, I dont think I can make the right reprex for this, but its about logarithmic performance degredation when increasing the filesize when reading in XML. I was wondering this behavior happens because I am not using the library as intended. Perhaps I am supposed to read large XML straight into List structure ??  Sorry for cross-post, trying to keep it a usage question first. Or perhaps I am catching a bug ? 

Here is the post

https://community.rstudio.com/t/xml2-library-question-about-correct-usage-of-library-or-have-i-found-a-bug-related-to-performance/60443

 
or shall we can turn this into a reprex ....

Peter

```r
# insert reprex here
```

**Comment by jimhester** [comment]
This doens't seem to be an issue in the package, I think the response at https://community.rstudio.com/t/xml2-library-question-about-correct-usage-of-library-or-have-i-found-a-bug-related-to-performance/60443/4 sounds like the correct approach. You should write XPATH expressions to pull out the data you need.
