### ISSUE TITLE
Where did xml2:::xpath_search go?

### ISSUE THREAD

**Issue by mem48** [r-lib/xml2#299]
I have some very irregularly structured XML files that I'm trying to read in. Often the values I need are missing, and `xml2` will skip over missing values.

I want to find all instances of a child and return its value, but if it is missing return an NA. This kept the lengths of the results constant so I can match up different children later.

So I wrote a little function.

```
import_simple_xml <- function(xml1, nm) {
  if (length(xml1) == 0) {
    return(xml1)
  }
    nodes <- lapply(xml1, function(x) {
    res <- xml2:::xpath_search(x$node,
      x$doc,
      xpath = nm,
      nsMap = xml2::xml_ns(x),
      num_results = Inf
    )

    if (length(res) == 0) {
      return(NA)
    } else if (length(res) == 1) {
      res <- xml2::xml_text(res[[1]])
      return(res)
    } else {
      stop("res is not of length 0 or 1")
    }
  })
  nodes <- unlist(nodes, recursive = FALSE)
  return(nodes)
}
```

It used `xml2:::xpath_search`, but after updating the package, this function seems to have been removed.

I know using `:::` is not best practice, but I was the only way I could find to get the results I needed.

Is there an alternative function or method I can use to get the same results?

**Comment by mem48** [comment]
I've been rooting thought the code, and as far as I can tell the change is that `xml2:::xpath_search`  has been replaced with `.Call(xpath_search)`

A possible solution is a small change to `xml_find_all` I can make a pull request if you like?

```
xml_find_all.xml_nodeset <- function(x, xpath, ns = xml_ns(x), keep_na = FALSE) {
  if (length(x) == 0)
    return(xml_nodeset())
  
  nodes <-  lapply(x, function(x)
    .Call(xpath_search, x$node, x$doc, xpath, ns, Inf))
  
  if(keep_na){
    nodes <- lapply(nodes, function(x){
      if(is.null(x)){
        return(NA)
      } else{
        return(x)
      }
    })
  }
  
  nodes <-unlist(nodes, recursive = FALSE) 
  xml_nodeset(nodes)
}
```

**Comment by jimhester** [comment]
What I think you want is to use `xml_find_first()` on the results of `xml_find_all()`, e.g.

``` r
library(xml2)
data <- read_xml(
"<trees>
  <tree>
    <name>Apple tree</name>
    <fruit>Apple</fruit>
  </tree>
  <tree>
    <name>Pine tree</name>
  </tree>
</trees>")

trees <- xml_find_all(data, "//tree")

names <- xml_find_first(trees, "./name")
names
#> {xml_nodeset (2)}
#> [1] <name>Apple tree</name>
#> [2] <name>Pine tree</name>

fruits <- xml_find_first(trees, "./fruit")

fruits
#> {xml_nodeset (2)}
#> [1] <fruit>Apple</fruit>
#> [2] <NA>
```

<sup>Created on 2020-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mem48** [comment]
Thanks your solution worked with a little tweaking.
