### ISSUE TITLE
xml2 installation on R 4.0.0

### ISSUE THREAD

**Issue by gabrielkaufman** [r-lib/xml2#306]
When attempting to install xml2 package on R 4.0.0 I receive an error message.

Please find below the complete console output. Please advise.

#######################

> install.packages("xml2")
Installing package into ‘C:/Users/gkaufman/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
     binary source needs_compilation
xml2  1.3.1  1.3.2              TRUE

installing the source package ‘xml2’

trying URL 'https://mirror.its.dal.ca/cran/src/contrib/xml2_1.3.2.tar.gz'
Content type 'application/x-gzip' length 271876 bytes (265 KB)
downloaded 265 KB

* installing *source* package 'xml2' ...
** package 'xml2' successfully unpacked and MD5 sums checked
** using staged installation
** libs
rm -f connection.o init.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o xml2.dll
"C:/PROGRA~1/R/R-40~1.0/bin/x64/Rscript.exe" "../tools/winlibs.R" 2.9.8
"c:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-40~1.0/include" -DNDEBUG -I../inst/include -I../windows/libxml2-2.9.8/include/libxml2 -DLIBXML_STATIC         -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c connection.cpp -o connection.o
sh: c:/rtools40/mingw64/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-40~1.0/etc/x64/Makeconf:229: connection.o] Error 127
ERROR: compilation failed for package 'xml2'
* removing 'C:/Users/gkaufman/Documents/R/win-library/4.0/xml2'

The downloaded source packages are in
        ‘C:\Users\gkaufman\AppData\Local\Temp\RtmpY7Ifml\downloaded_packages’
Warning message:
In install.packages("xml2") :
  installation of package ‘xml2’ had non-zero exit status
>

**Comment by jimhester** [comment]
There is not yet a binary build for xml2 1.3.2 on Windows. You would need to have Rtools installed to build source packages, wait for the binary, or answer no to the prompt when asked if you want to install binary packages or use the source version.
