### ISSUE TITLE
How to get html and xml structures into vectors?

### ISSUE THREAD

**Issue by lbocken** [r-lib/xml2#308]
I would like to get the html and xml structures into a vector. I tried but vectors are 'NULL'.

```r
URL <- 'https://en.wikipedia.org/wiki/Dog'
htmlStructure <- GetHTMLStructureFromURL(URL)
xmlStructure <- GetXMLStructureFromURL(URL)
 
GetHTMLStructureFromURL <- function(URL){
  library(xml2)
  htmlFile <- xml2::read_html(URL)
  htmlStructure <- xml2::html_structure(htmlFile)
  return(htmlStructure)
}

GetXMLStructureFromURL <- function(URL){
  library(xml2)
  xmlFile <- xml2::read_xml(URL)
  xmlStructure <- xml2::xml_structure(xmlFile)
  return(xmlStructure)
}
```

**Comment by cderv** [comment]
See `?xml2::xml_structure`: the function returns nothing, just an invisible NULL. 
There is a `file`argument that allow you to write to a file. I think if you use that, you can read back the content as a character vector if you want. 

Hope it helps.

**Comment by lbocken** [comment]
The file argument works well but I would prefer to avoid this step if it's possible. I am sure that there is a way to get directly the html or xml structures inside a vector but I don't understand all the details behind these functions : https://rdrr.io/github/hadley/xml2/src/R/xml_structure.R but NULL return seems related to the function 'cat'. Maybe I have to change the behavior of the function 'cat' or maybe I have to build another similar function with another function than the function 'cat'...

Thank you very much for your help !

**Comment by jimhester** [comment]
You can use `capture.output()` or the `file` argument to `xml_structure()` as suggested.
