### ISSUE TITLE
[RFE] url_parse: split the "server" name in more parts

### ISSUE THREAD

**Issue by dmedri** [r-lib/xml2#309]
url_parse has a "server" part. It could be helpful have a list of subdomain, tld, domain name.

url: http://a.b.c.google.com:80/u@b/a/b/c/v1=1&v2=2

The server part is now "a.b.c.google.com".
What could nice have:
- a list of sub-domains
[1] "a" "b" "c"
- a tld
[1] "com"
- a domain name
[1] "google"

HTH

**Comment by jimhester** [comment]
`url_parse()` is a wrapper around the libxml2 function [xmlParseURI](http://xmlsoft.org/html/libxml-uri.html#xmlParseURI). I don't think the R package should try to support additional functionality for this particular function outside of what is offered by libxml2.

One way for you to get this data is to use a special purpose package like [urltools](https://cran.r-project.org/package=urltools)

``` r
x <- urltools::url_parse("http://abc.google.com:80/u/a/b/c/v1=1&v2=2")
urltools::suffix_extract(x$domain)
#>             host subdomain domain suffix
#> 1 abc.google.com       abc google    com
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dmedri** [comment]
urltools is fine, but I need to split just that info. I'll write some gsub rules. Thank you!
