### ISSUE TITLE
Why is it invalid to generate the target filename when you change the makefile XML_NAME to xml2d?

### ISSUE THREAD

**Issue by mirro187** [r-lib/xml2#310]
`
AUTOCONF = .\config.msvc
!include $(AUTOCONF)

# Names of various input and output components.

XML_NAME = xml2
XML_BASENAME = lib$(XML_NAME)
XML_SO = $(XML_BASENAME).dll
XML_IMP = $(XML_BASENAME).lib
XML_DEF = $(XML_BASENAME).def
XML_A = $(XML_BASENAME)_a.lib
XML_A_DLL = $(XML_BASENAME)_a_dll.lib
`

**Comment by jimhester** [comment]
This is the repo for the xml2 R package, which wraps libxml2.

If this issue is for libxml2 itself you need to open it at https://gitlab.gnome.org/GNOME/libxml2/-/issues
