### ISSUE TITLE
Using rvest for web scraping

### ISSUE THREAD

**Issue by Anestis-K** [r-lib/xml2#313]
When i am trying to convert my second piece of code into text i come up again with the same error: Error in xml_ns.xml_document(x) : external pointer is not valid . I took the element from developer tools and the element seems right. The other problem is that yesterday this piece of code worked perfectly. I did some research and it seems that has updated(the element , the website) , i do not know exactly . 
Any help is appreciated
Thank you

```r
library('rvest')
Ratings_count_html <- html_nodes(webpage, 'ratings-count')
Ratings_count <- html_text(Ratings_count_html)
```

**Comment by jimhester** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)

**Comment by Anestis-K** [comment]
Thank you @jimhester
