### ISSUE TITLE
feature request: read_html, read_xml.character argument to always parse the string directly

### ISSUE THREAD

**Issue by patr1ckm** [r-lib/xml2#314]
When parsing a string that possibly contains HTML, `read_html` attempts to read the character string as a file if it does not contain any html tags: 

```
read_html('asfd')
Error: 'asfd' does not exist in current working directory ('...').
```

This comes from `read_xml.character` where the following dispatch takes place:
```
 if (grepl("<|>", x)) {
        read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html, 
            options = options)
    }
```

It would be nice if the user could control this behavior with an argument, e.g. to always force `read_html` to attempt to parse a string as raw HTML instead of a path. This would also solve the problem above that arises with the solution given in [this stackoverflow answer](https://stackoverflow.com/a/34344957/786220).

**Comment by jimhester** [comment]
The easiest way around this is to pass the argument as a raw vector instead.

e.g.

``` r
xml2::read_html(charToRaw('asfd'))
#> {html_document}
#> <html>
#> [1] <body><p>asfd</p></body>
```

<sup>Created on 2020-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by patr1ckm** [comment]
Ah, I was stumbling around the connection functions and didn't get to `charToRaw`. Thank you, so handy! Feel free to close!
