### ISSUE TITLE
Re-licensing xml2

### ISSUE THREAD

**Issue by hadley** [r-lib/xml2#317]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/xml2/graphs/contributors). @ddiez, @heckendorfc, @HenrikBengtsson, @hrbrmstr, @jakejh, @michaelquinn32, @nuest, @renkun-ken, @richfitz, @shabbychef, @sjp, would you permit us to re-license xml2 with the MIT license? If so, please comment "I agree" below.

* [x] [@ddiez](https://github.com/r-lib/xml2/commits?author=ddiez)  
* [x] [@heckendorfc](https://github.com/r-lib/xml2/commits?author=heckendorfc)  
* [x] [@HenrikBengtsson](https://github.com/r-lib/xml2/commits?author=HenrikBengtsson)  
* [x] [@hrbrmstr](https://github.com/r-lib/xml2/commits?author=hrbrmstr)  
* [x] [@jakejh](https://github.com/r-lib/xml2/commits?author=jakejh)  
* [x] [@michaelquinn32](https://github.com/r-lib/xml2/commits?author=michaelquinn32)  
* [x] [@nuest](https://github.com/r-lib/xml2/commits?author=nuest)  
* [x] [@renkun-ken](https://github.com/r-lib/xml2/commits?author=renkun-ken)  
* [x] [@richfitz](https://github.com/r-lib/xml2/commits?author=richfitz)  
* [x] [@shabbychef](https://github.com/r-lib/xml2/commits?author=shabbychef)  
* [x] [@sjp](https://github.com/r-lib/xml2/commits?author=sjp)

**Comment by renkun-ken** [comment]
I agree

**Comment by heckendorfc** [comment]
I agree

**Comment by jakejh** [comment]
I agree.

**Comment by shabbychef** [comment]
I agree.

**Comment by ddiez** [comment]
I agree.

**Comment by HenrikBengtsson** [comment]
approve.

**Comment by richfitz** [comment]
I agree.

**Comment by hrbrmstr** [comment]
I agree

**Comment by sjp** [comment]
I agree

**Comment by michaelquinn32** [comment]
I agree.

**Comment by batpigandme** [comment]
Hi @nuest,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by nuest** [comment]
I agree.

**Comment by HenrikBengtsson** [comment]
I agree
