### ISSUE TITLE
transitive digest (R>=3.3) dependency breaks R 3.2 pipeline

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/xml2#325]
Observed here:

https://github.com/r-lib/xml2/pull/324/checks?check_run_id=1451803924

`digest` recently bumped to 3.3:

https://github.com/eddelbuettel/digest/issues/159

I guess it's `covr` that generates the transitive dependency (I'm not sure if there others). Would it be easy to skip installing `covr` on that build?

**Comment by jimhester** [comment]
I think we can disable checking on 3.2 build. We generally commit to supporting the last 4 minor releases of R in the tidyverse / r-lib packages, which is now 3.3+.
