### ISSUE TITLE
Creating customized self-closing tags like <hr> and <br> for HTML documents

### ISSUE THREAD

**Issue by djd0723** [r-lib/xml2#334]
Tags like \<hr\> and \<br\> are automatically considered self-closing tags. Unlike most html tags, they do not require \</hr\> or \</br\> to close them out. I would like to be able to add self-closing tags with custom names, such as \<ChapterEnd\> or \<PageEnd\>. I have looked through a lot of documentation, but cannot find any possible way to do this. Any help would be appreciated. Thank you.

**Comment by jimhester** [comment]
The list of self-closing tags for HTML is part of the spec and is fixed, you cannot define additional tags.

For XML or XHTML (not HTML) documents, any tag can be self-closing by using `<mytag />` syntax.
