### ISSUE TITLE
xml2 installation fail, libxml2 installed, no anaconda, R 4.0.4

### ISSUE THREAD

**Issue by Skypeblue** [r-lib/xml2#335]
Hello 
I want to install the package lm and in order to do that, I need the package xml2 which failed every time. I am on the Linux distribution Solus 4.2 Fortitude with the version 4.0.4 of R installed without anaconda and I already downloaded the package libxml2 and libxml2-devel, but it failed every time  

I have the following output during the installation : 
* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/libxml2
Using PKG_LIBS=-lxml2 -lz -llzma -lm -ldl
** libs
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c connection.cpp -o connection.o
x86_64-solus-linux-gcc -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include   -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c init.c -o init.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_doc.cpp -o xml2_doc.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_init.cpp -o xml2_init.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_namespace.cpp -o xml2_namespace.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_node.cpp -o xml2_node.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_output.cpp -o xml2_output.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_schema.cpp -o xml2_schema.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_url.cpp -o xml2_url.o
x86_64-solus-linux-g++ -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include -I/usr/include/libxml2 -DUCHAR_TYPE=wchar_t  -I/usr/local/include  -fvisibility=hidden -fpic  -mtune=generic -march=x86-64 -g2 -pipe -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -fno-semantic-interposition -O3 -falign-functions=32  -c xml2_xpath.cpp -o xml2_xpath.o
x86_64-solus-linux-g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000 -Wl,-Bsymbolic-functions -Wl,--sort-common -o xml2.so connection.o init.o xml2_doc.o xml2_init.o xml2_namespace.o xml2_node.o xml2_output.o xml2_schema.o xml2_url.o xml2_xpath.o -lxml2 -lz -llzma -lm -ldl -L/usr/lib64/R/lib -lR
/usr/bin/ld: cannot find -llzma
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/make/shlib.mk:10: xml2.so] Error 1
ERROR: compilation failed for package ‘xml2’
* removing ‘/home/fredo/Rlibs/xml2’

The downloaded source packages are in
	‘/tmp/RtmpUKRqHf/downloaded_packages’
Warning message:
In install.packages("xml2") :
  installation of package ‘xml2’ had non-zero exit status
  
I have already chevk this topic : https://github.com/r-lib/xml2/issues/223 and check every solutions, but it failed. However I did not try to reinstall manually since on one hand, the url doesn't work, even in the official website and on other hand, the version of libxml2 is more recent, according this ouput 
lrwxrwxrwx 1 root root      17 Feb  1 13:29 /usr/lib/libxml2.so -> libxml2.so.2.9.10
lrwxrwxrwx 1 root root      17 Feb  1 13:28 /usr/lib/libxml2.so.2 -> libxml2.so.2.9.10
-rwxr-xr-x 1 root root 1348784 Jan 23 09:45 /usr/lib/libxml2.so.2.9.10

I don't test answers linked to anaconda since I don't have it, so I deduced the problem is not with it.

I test to install by devtools, but the installation of devtools require xml2, so I can't test this path.

**Comment by jimhester** [comment]
`/usr/bin/ld: cannot find -llzma` looks like the isuse.

Seems like `pkg-config` is trying to link with `-llzma` but you don't have this system library installed.

**Comment by Skypeblue** [comment]
Thanks a lot, I thought it was a binary file created during the installation. I install the package xz-devel and it worked.
