### ISSUE TITLE
read_xml() fails  with ampersand

### ISSUE THREAD

**Issue by josh-maccarty** [r-lib/xml2#336]
When trying to read an xml using read_xml() with an ampersand "&" anywhere throws this error where tex.xml is the file name. I know XML parsing struggles with &, but anyway to turn & into something else before/in the read process?

Error in read_xml.character("test.xml") : xmlParseEntityRef: no name [68]

**Comment by jimhester** [comment]
`&` is an escape character in XML, so they would need to be `&amp;` to be valid XML

**Comment by jimhester** [comment]
It is possible you could try using `xml2::read_xml("test.xml", options = "NOENT")` to replace entities. 

If you could provide a reproducible example it would help us assist you.

**Comment by josh-maccarty** [comment]
It is as a <title> </title> in a valid XML without the "amp;" following the "&" -- I do not know how it was created like that though, as I try to make a reproducible example in R it doesn't allow it. Its one of many XML and when I go in and add 'amp;' by hand it solves the problem but obviously going through by hand when this occurs is a pain. -- Not your fault, or problem though!

**Comment by MichaelChirico** [comment]
FWIW, I came across this issue trying to convert some code that's using `XML::htmlParse()`, doing so with `xml2::read_xml()` is proving a bit tricky:

```r
str = '<p>A & B</p>'

XML::htmlParse("<p>A & B</p>", asText = TRUE)
# <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
# <html><body><p>A &amp; B</p></body></html>
 
xml2::read_xml("<p>A & B</p>")
# Error in read_xml.raw(charToRaw(enc2utf8(x)), "UTF-8", ..., as_html = as_html,  : 
#   xmlParseEntityRef: no name [68]
```

Unfortunately the code is also used to deparse HTML entities, so simply `gsub("&", "&amp;", x, fixed = TRUE)` won't work either, I'll have to come up with some more complicated logic to swap `&` to `&amp;` as needed. It would be nice if `xml2` could handle this instead as I'm likely to fall short on matching the `htmlParse()` behavior here.

(`options = "NOENT"` doesn't help btw)
