### ISSUE TITLE
Error loading xml2 

### ISSUE THREAD

**Issue by WLonghini** [r-lib/xml2#343]
I have a error msg when trying load xml2; I'm in linxu debian 10 and R 4.10; 
...
Erro: package or namespace load failed for ‘xml2’ in dyn.load(file, DLLpath = DLLpath, ...):
 impossível carregar objeto compartilhado '/home/usuario/R/x86_64-pc-linux-gnu-library/4.1/xml2/libs/xml2.so':
  /home/usuario/R/x86_64-pc-linux-gnu-library/4.1/xml2/libs/xml2.so: symbol htmlReadFile version LIBXML2_2.6.0 not defined in file libxml2.so.2 with link time reference
...

Some idea how to fix it?

Tks

**Comment by WLonghini** [comment]
I tryed, but doesn't work for me. I have de R 4.1.1 installed and the xml2 version 2.9.4+dfsg1-7+deb10u2.

**Comment by hadley** [comment]
This is probably likely to be related to how your linux distro is configured, but unfortunately I don't know what the problem is.
