### ISSUE TITLE
`ERROR: libicui18n.so.58: cannot open shared object file: No such file or directory`

### ISSUE THREAD

**Issue by danli349** [r-lib/xml2#357]
Hello,

I am trying to install `xml2` in `R` by
```r
install.packages("xml2", lib='~/R/x86_64-pc-linux-gnu-library/4.0')
```
But

```r
Error :  unable to load shared object '/lila/home/lid/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-xml2/00new/xml2/libs/xml2.so':
  libicui18n.so.58: cannot open shared object file: No such file or directory
ERROR: installing Rd objects failed for package 'xml2'
```
Can someone tell me what is wrong with the install and what should I do to install it?

Thanks a lot

**Comment by danli349** [comment]
I solved this problem by (https://github.com/r-lib/xml2/issues/219)

**Comment by TomGeens** [comment]
I call conda deactivate in the terminal window before starting R and installing packages like XML, xml2 or RCurl.
