### ISSUE TITLE
xml2 macOS Monterey automatization with Cron does not work

### ISSUE THREAD

**Issue by SwissMontainsBear** [r-lib/xml2#367]
Hi,

Thanks for developing and supporting xml2. This is awesome.

I am using xml2 to parse 'xls' files downloaded every day. I am trying to automate this process using cron on a Mac.
I noticed that the process is interrupted as soon as the "read_xml" instruction is executed. I suspect that this is due to macOS "sandboxing" the libxml2 calls, as the installation directory of xml2 package is "/opt/homebrew/lib/R/4.2/site-library/00LOCK-xml2/00new/xml2/libs".

Is there any compilation option for the package which could be used in order to avoid this behavior and allow the automated execution of the Rscript including this xml2 call ?

Thanks in advance.

**Comment by hadley** [comment]
No ideas sorry 😞
