### ISSUE TITLE
xml2 locks the XML file if the file has XML syntax error

### ISSUE THREAD

**Issue by jmendys** [r-lib/xml2#382]
Steps to reproduce 
1. Create an XML file with an invalid structure for example <?xml version="1.0" encoding="UTF-8"?><body><openTag></body>
2. Open the file with xml2::read_xml() command

Expected behavior:
- an error is displayed
- the process is terminated

Actual behavior:
- an error is displayed
- the input XML file is locked (can't be modified or deleted) until R session is restarted (the process seems to continue in the background in a separate thread)
- if you keep calling xml2::read_xml() the R studio will eventually crash.

**Comment by hadley** [comment]
I think this is likely an interaction between libxml2 and windows that unfortunately there's nothing we can do about.

**Comment by hadley** [comment]
Actually this looks like #376
